import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
// import { Geist, Geist_Mono } from "next/font/google";
// import LogoutButton from "@/app/component/LogoutButton";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
      <ToastContainer position="top-right" autoClose={3000} closeOnClick />
    </>
  );
}
