import type { Metadata } from "next";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { useState } from "react";
import PopupMenu from "./component/PopupMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html className="bg-black" lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <nav className="bg-gray-800 text-white p-2 fixed w-full top-0 shadow-md z-10 flex justify-end">
            <ul className="flex space-x-3 cursor-pointer">
              <li className="bg-slate-600 px-5 py-2 rounded-xl">
                <PopupMenu />
              </li>
            </ul>
          </nav>

        </body>
      </html>

      {children}
    </>
  );
}


